### ISSUE TITLE
Transliteration from Arabic not working for continuous text

### ISSUE THREAD

**Issue by twardoch** [kbatsuren/wiktra#7]
Transliteration from Arabic is not working for continuous text. It works for single space-separated characters. The Arabic Wiktionary module is a bit complex, need to investigate and add some special processing.

**Comment by kbatsuren** [comment]
Should I implement preprocessing and postprocessing functions in this case? It is like tokenizing continuous text in preprocessing and concat the transliteration results in postprocessing.

**Comment by twardoch** [comment]
I think it’d be best to find out WHY it’s happening. There are multiple modules: 

- https://en.wiktionary.org/wiki/Module:ar-translit
- https://en.wiktionary.org/wiki/Module:ks-Arab-translit
- https://en.wiktionary.org/wiki/Module:fa-translit
- https://en.wiktionary.org/wiki/Module:pa-Arab-translit

`ar-translit` has an unusual `tr` function: `function export.tr(text, lang, sc, omit_i3raab, gray_i3raab, force_translit)`. 

I could try to find out how to deal with this, or you might :) 

We ought

**Comment by skalyan91** [comment]
Arabic transliteration does not work for me even for single characters. If I run `wiktrapy -l ar -t "ا"`, I get the following output:
```
Traceback (most recent call last):
  File "~/.local/bin/wiktrapy", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.9/site-packages/wiktra/__main__.py", line 97, in main
    res = tr.tr(
  File "~/.local/lib/python3.9/site-packages/wiktra/Wiktra.py", line 298, in tr
    res = self.e(
  File "~/.local/lib/python3.9/site-packages/wiktra/Wiktra.py", line 243, in e
    self.lua.execute(lua_str)
  File "lupa/_lupa.pyx", line 280, in lupa._lupa.LuaRuntime.execute
  File "lupa/_lupa.pyx", line 1297, in lupa._lupa.run_lua
  File "lupa/_lupa.pyx", line 1306, in lupa._lupa.call_lua
  File "lupa/_lupa.pyx", line 1332, in lupa._lupa.execute_lua_call
  File "lupa/_lupa.pyx", line 1268, in lupa._lupa.raise_lua_error
lupa._lupa.LuaError: ...on3.9/site-packages/wiktra/wikt/translit/ar-translit.lua:332: attempt to call a nil value (global 'unpack')
stack traceback:
	...on3.9/site-packages/wiktra/wikt/translit/ar-translit.lua:332: in upvalue 'has_diacritics'
	...on3.9/site-packages/wiktra/wikt/translit/ar-translit.lua:219: in function 'wikt.translit.ar-translit.tr'
	[string "<python>"]:1: in main chunk
```

Funnily, I don’t get this error if I set the language to `fa` (Farsi); but it also doesn’t transliterate the input either.

Hebrew results in the same error as Arabic. Meanwhile I have no trouble with Indic writing systems.

**Comment by skalyan91** [comment]
I would add that when the language is set as `fas` (Persian), even single letters are not transliterated.

**Comment by twardoch** [comment]
Yeah, there are a few different Arabic-script transliterators and the whole notion of Arabic needs some special handling in our Py code.
